import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee"
const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",

  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <Marquee/>
        <main className="max-w-6xl mx-auto">{children}</main>
        <div>Footer</div>
      </body>
    </html>
  );
}
